rabbitmq-transport
otuskotlin/202302-ok-marketplace pull request #18
Opened 2023-04-26 22:19 UTC by DarkSide2018

created rabbit mq tests

2023-04-27 03:44 UTC, svok requested changes
Несколько мелочей надо поправить

2023-04-27 03:44 UTC, svok commented on ok-marketplace-app-rabbit/src/main/kotlin/ru/otus/otuskotlin/marketplace/app/rabbit/controller/RabbitController.kt
> +                Executors.newSingleThreadExecutor()
```suggestion
                Dispatchers.IO.limitedParallelism(1)
```

2023-04-27 03:44 UTC, svok commented on ok-marketplace-app-rabbit/src/main/kotlin/ru/otus/otuskotlin/marketplace/app/rabbit/controller/RabbitController.kt
> +    fun start() = scope.launch {
Зачем запускать в отдельном скоупе всю функцию, если все ее части тоже будут отправлены в отдельный скоуп?
Думаю, можно спокойно удалить scope

2023-04-27 03:44 UTC, svok commented on ok-marketplace-app-rabbit/src/main/kotlin/ru/otus/otuskotlin/marketplace/app/rabbit/processor/RabbitDirectProcessor.kt
> +        val response = processor.exec(context).run { context.toTransportAd() }
Не вижу смысла в такой конструкции. exec возвращает Unit. На Unit навешивать run... Зачем?
Лучше спокойно и без перегруза функциональщиной разбить на две строки.

2023-04-28 10:41 UTC, evgnep commented
Добавь еще создание докер-образа в грейдл

2023-04-28 10:54 UTC, evgnep commented
И еще момент - мы ветки называем по номеру занятия, например `m3l2-ktor`

2023-04-28 10:56 UTC, DarkSide2018 commented
Принято

2023-04-30 06:11 UTC, evgnep commented on ok-marketplace-app-rabbit/src/main/kotlin/ru/otus/otuskotlin/marketplace/app/rabbit/controller/RabbitController.kt
> +class RabbitController {
А куда делась работа с рабитом?

2023-04-30 12:35 UTC, DarkSide2018 commented on ok-marketplace-app-rabbit/src/main/kotlin/ru/otus/otuskotlin/marketplace/app/rabbit/controller/RabbitController.kt
> +class RabbitController {
я все добавил, вчера не успел

2023-05-01 06:29 UTC, evgnep requested changes
Плюс см обсуждение в общем чате, давай там дообсудим концепцию

2023-05-01 06:29 UTC, evgnep commented on settings.gradle.kts
> +    val springframeworkBootVersion:String by settings
верни пробелы - чем меньше правок по форматированию в чужом коде, тем потом проще все это мержить и переносить

2023-05-01 06:29 UTC, evgnep commented on settings.gradle.kts
> -//include("m1l1-hello")
и это тоже верни - иногда надо что-то быстро включить, удобней просто раскомментить

2023-05-01 06:33 UTC, evgnep commented on ok-marketplace-app-rabbit/build.gradle.kts
> +apply(plugin = "com.bmuschko.docker-remote-api")
а это зачем? ты же уже его применил выше в plugins

2023-05-01 06:33 UTC, evgnep commented on ok-marketplace-app-rabbit/build.gradle.kts
> +apply(plugin = "com.bmuschko.docker-remote-api")
плюс мне кажется нужен вот этот com.bmuschko.docker-java-application
или ты проверял и работает?

2023-05-01 11:45 UTC, closed without merging