fixed test and application
otuskotlin/202302-ok-marketplace pull request #21
Opened 2023-05-01 11:44 UTC by DarkSide2018

2023-05-01 19:54 UTC, evgnep commented on ok-marketplace-app-rabbit/build.gradle.kts
> +    id ("com.bmuschko.docker-java-application")
по моему надо таки и настроить его - по дефолту используется `Step 1/8 : FROM openjdk:11.0.15-jre-slim` и образ в результате не запускается 
```
Error: LinkageError occurred while loading main class ru.otus.otuskotlin.marketplace.app.rabbit.ApplicationKt
        java.lang.UnsupportedClassVersionError: ru/otus/otuskotlin/marketplace/app/rabbit/ApplicationKt has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```

2023-05-01 19:54 UTC, evgnep requested changes
Плюс глянь тесты - они падают....

2023-05-03 17:42 UTC, DarkSide2018 commented
Тесты я смотрел, локально запускаются - я починил. Почему тут не запускаются непонятно. Тесты падают именно на подключении к рэббит

2023-05-03 20:12 UTC, evgnep submitted a review, later dismissed

2023-05-19 20:08 UTC, merged